package com.liy.blendlib.core.animation.v2;

/** Bounded internal diagnostics; these do not allocate or change any v1 stable error-code family. */
public enum AnimationV2DiagnosticCode {
    EMPTY_MASK,
    ZERO_WEIGHT_LAYER,
    LOWER_PRIORITY_OVERRIDE_SUPPRESSED,
    OVERLAPPING_OVERRIDE,
    COMPETING_CONTROLLER_WRITE,
    EXCLUSIVE_WRITE_CONFLICT,
    NEXT_CYCLE,
    NEXT_TRANSITION_BUDGET,
    OBSERVER_TRAVERSAL_TRUNCATED,
    STALE_COMMAND,
    COMMAND_SEQUENCE_CONFLICT,
    COMMAND_DUPLICATE_DROPPED,
    COMMAND_RATE_REJECTED,
    COMMAND_INGRESS_QUEUE_OVERFLOW,
    COMMAND_DRAIN_BUDGET_EXHAUSTED,
    ADVANCE_DELTA_CLAMPED,
    DIAGNOSTICS_TRUNCATED
}
