# SPDX-FileCopyrightText: 2026 BlendLib local project
# SPDX-License-Identifier: GPL-3.0-or-later

"""Verify parser isolation plus two-run normalized fixture determinism."""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Must happen before importing the exporter: repeated Blender verification runs
# are required to leave the source checkout free of generated bytecode.
sys.dont_write_bytecode = True

ADDON_ROOT = Path(__file__).resolve().parents[1]
if str(ADDON_ROOT) not in sys.path:
    sys.path.insert(0, str(ADDON_ROOT))

from blendlib_exporter import (  # noqa: E402
    ExportError,
    parse_blender_arguments,
    read_glb,
    run_cli,
    validate_glb,
    write_glb,
)


def _load_expected(root: Path, fixture: str) -> dict:
    return json.loads((root / "test-assets" / fixture / "expected.json").read_text(encoding="utf-8"))


def _assert_parser_ignores_pre_separator(root: Path) -> None:
    expected = _load_expected(root, "static")
    options = parse_blender_arguments(
        [
            "blender.exe",
            "--background",
            "--blend",
            "SHOULD_NOT_BE_PARSED.blend",
            "--",
            "--blend",
            str(root / "test-assets" / "static" / "source.blend"),
            "--project-root",
            str(root / "build" / "p2-parser-isolation"),
            "--namespace",
            expected["namespace"],
            "--model-id",
            expected["model_id"],
            "--profile",
            expected["profile"],
            "--collection",
            expected["collection"],
        ]
    )
    assert options.blend_path == (root / "test-assets" / "static" / "source.blend").resolve()
    try:
        parse_blender_arguments(["blender.exe", "--blend", "missing.blend"])
    except ExportError as error:
        assert error.code == "BLENDLIB-CLI-001"
    else:
        raise AssertionError("Missing '--' separator was accepted")


def _assert_source_tree_hygiene(root: Path) -> None:
    unexpected = []
    for directory, patterns in (
        (root / "blender-addon", ("*.pyc", "*.blend1")),
        (root / "test-assets", ("*.pyc", "*.blend1")),
    ):
        for pattern in patterns:
            unexpected.extend(path.relative_to(root).as_posix() for path in directory.rglob(pattern))
    assert not unexpected, f"Source-tree generated artifacts are forbidden: {sorted(unexpected)}"


def _run_fixture(root: Path, fixture: str, output: Path) -> dict:
    expected = _load_expected(root, fixture)
    options = parse_blender_arguments(
        [
            "blender.exe",
            "--background",
            "--",
            "--blend",
            str(root / "test-assets" / fixture / "source.blend"),
            "--project-root",
            str(output),
            "--namespace",
            expected["namespace"],
            "--model-id",
            expected["model_id"],
            "--profile",
            expected["profile"],
            "--collection",
            expected["collection"],
            "--report",
            "report.json",
        ]
    )
    result = run_cli(options)
    persisted = json.loads((output / "report.json").read_text(encoding="utf-8"))
    assert persisted["normalized_structure"] == result["normalized_structure"]
    assert result["validation"]["embedded_runtime_images"] is False
    assert result["validation"]["animation_names"] == expected["expected_animation_names"]
    _assert_descriptor_png_resources(result, expected)
    if fixture == "static":
        assert result["validation"]["world_bounds"] == expected["expected_canonical_bounds"]
    return result


def _assert_descriptor_png_resources(result: dict, expected: dict) -> None:
    """Assert exact descriptor-to-file mapping without adapter inference."""

    descriptor_path = Path(result["descriptor_path"])
    descriptor = json.loads(descriptor_path.read_text(encoding="utf-8"))
    assets_root = descriptor_path.parents[2]
    resources = set()
    for material_name, material in descriptor["materials"].items():
        resource = material["base_color"]
        resources.add(resource)
        namespace, relative_path = resource.split(":", 1)
        assert namespace == result["namespace"], resource
        assert relative_path.startswith("textures/"), resource
        assert relative_path.endswith(".png"), resource
        copied_file = assets_root / relative_path
        assert copied_file.is_file(), copied_file
        assert copied_file == Path(result["texture_paths"][material_name]), material_name
    assert resources == {expected["expected_base_color"]}, resources


def _assert_cubicspline_rejected(result: dict) -> None:
    mesh_path = Path(result["mesh_path"])
    gltf, binary = read_glb(mesh_path)
    gltf["animations"][0]["samplers"][0]["interpolation"] = "CUBICSPLINE"
    mutated = mesh_path.with_name("unexpected-cubicspline.glb")
    write_glb(mutated, gltf, binary)
    try:
        validate_glb(
            mutated,
            profile=result["profile"],
            expected_animation_names=result["validation"]["animation_names"],
            expected_bounds=result["source_bounds"],
            expected_material_names=result["validation"]["material_names"],
            expected_source_node_names=[
                node["name"] for node in result["normalized_structure"]["glb"]["nodes"]
            ],
        )
    except ExportError as error:
        assert error.code == "BLENDLIB-ANIM-006", error
    else:
        raise AssertionError("CUBICSPLINE mutation was accepted")


def main() -> None:
    if "--" not in sys.argv:
        raise SystemExit("Arguments must follow '--'.")
    args = sys.argv[sys.argv.index("--") + 1 :]
    if len(args) != 2 or args[0] != "--project-root":
        raise SystemExit("Usage: verify_p2_fixtures.py -- --project-root <root>")
    root = Path(args[1]).resolve()
    output_root = root / "build" / "p2-determinism"
    if output_root.exists():
        shutil.rmtree(output_root)
    _assert_source_tree_hygiene(root)
    _assert_parser_ignores_pre_separator(root)
    for fixture in ("static", "rigid", "skinned"):
        first = _run_fixture(root, fixture, output_root / fixture / "first")
        second = _run_fixture(root, fixture, output_root / fixture / "second")
        assert first["normalized_structure"] == second["normalized_structure"], fixture
        assert first["sha256"]["normalized_structure"] == second["sha256"]["normalized_structure"], fixture
        if fixture == "rigid":
            _assert_cubicspline_rejected(first)
    _assert_source_tree_hygiene(root)
    print("BLENDLIB_P2_DETERMINISM_PASS static rigid skinned")


if __name__ == "__main__":
    main()
