# SPDX-FileCopyrightText: 2026 BlendLib local project
# SPDX-License-Identifier: GPL-3.0-or-later

"""BlendLib Blender 5.x extension entrypoint."""

import sys

# Keep Blender extension imports from leaving generated bytecode in the source
# checkout. Headless entrypoints set the flag before importing this package too.
sys.dont_write_bytecode = True

from .blendlib_exporter import register, unregister

__all__ = ("register", "unregister")
